name: Update shivanshbakshi.dev
on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'prod'
    name: Update Site on Cloudflare Pages
    steps:
      - run: echo "Trigger cloudflare update using build hook"
      - shell: bash
        env:
          CLOUDFLARE_DEPLOY_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_TOKEN }}
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/$CLOUDFLARE_DEPLOY_TOKEN
      
      
