name: Update shivanshbakshi.dev
on: 
  push:
    branches:
      - master

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger netlify update using build hook"
      - shell: bash
        env:
          NETLIFY_BUILD_TRIGGER: ${{ secrets.NETLIFY_BUILD_TRIGGER }}
        run: |
          echo "curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_BUILD_TRIGGER"
      
      
